#[repr(C)]
#[allow(non_camel_case_types)]
pub enum cart_db_save_type {
    CART_DB_SAVE_TYPE_NONE,
    CART_DB_SAVE_TYPE_EEPROM_4KBIT,
    CART_DB_SAVE_TYPE_EEPROM_16KBIT,
    CART_DB_SAVE_TYPE_FLASH_1MBIT,
    CART_DB_SAVE_TYPE_SRAM_256KBIT,
    CART_DB_SAVE_TYPE_SRAM_768KBIT,
    CART_DB_SAVE_TYPE_SRAM_1MBIT,
}
pub use cart_db_save_type::*;

#[repr(C)]
#[allow(non_camel_case_types)]
pub struct cart_db_entry {
    pub rom_id: *const core::ffi::c_char,
    pub regions: *const core::ffi::c_char,
    pub save_type: cart_db_save_type,
    pub description: *const core::ffi::c_char,
}
// 1. Tell Rust this struct is safe to share between threads
// This is required for 'static' variables.
unsafe impl Sync for cart_db_entry {}
unsafe impl Send for cart_db_entry {}

extern "C" {
    /// Checks if the compiled-in C database is valid.
    pub fn cart_db_is_well_formed() -> bool;

    /// Scans the ROM header and returns the matching database entry.
    pub fn cart_db_get_entry(rom: *const u8) -> *const cart_db_entry;
}
// pub const NUM_CART_DB_ENTRIES: usize = core::mem::size_of_val(&CART_DB_TABLE) / core::mem::size_of::<cart_db_entry>();

pub const NUM_CART_DB_ENTRIES: usize =
    core::mem::size_of::<[cart_db_entry; CART_DB_TABLE.len()]>() / core::mem::size_of::<cart_db_entry>();

pub static CART_DB_TABLE: [cart_db_entry;180] = [
    cart_db_entry { rom_id: c"CDZ".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_768KBIT, description: c"Dezaemon 3D".as_ptr() },
    cart_db_entry { rom_id: c"CFZ".as_ptr(), regions: c"EJ".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"F-Zero X (NTSC)".as_ptr() },
    cart_db_entry { rom_id: c"CLB".as_ptr(), regions: c"EJ".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Mario Party (NTSC)".as_ptr() },
    cart_db_entry { rom_id: c"CP2".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Pokemon Stadium 2 (Japan)".as_ptr() },
    cart_db_entry { rom_id: c"CPS".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Pokemon Stadium (Japan)".as_ptr() },
    cart_db_entry { rom_id: c"CZL".as_ptr(), regions: c"EJ".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Legend of Zelda: Ocarina of Time (NTSC)".as_ptr() },
    cart_db_entry { rom_id: c"N3D".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Doraemon 3: Nobita no Machi SOS!".as_ptr() },
    cart_db_entry { rom_id: c"N3H".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Ganbare! Nippon! Olympics 2000".as_ptr() },
    cart_db_entry { rom_id: c"NA2".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Virtual Pro Wrestling 2".as_ptr() },
    cart_db_entry { rom_id: c"NAB".as_ptr(), regions: c"JP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Air Boarder 64".as_ptr() },
    cart_db_entry { rom_id: c"NAD".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Worms Armageddon (USA)".as_ptr() },
    cart_db_entry { rom_id: c"NAF".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Doubutsu no Mori".as_ptr() },
    cart_db_entry { rom_id: c"NAG".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"AeroGauge".as_ptr() },
    cart_db_entry { rom_id: c"NAL".as_ptr(), regions: c"EJPU".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Super Smash Bros".as_ptr() },
    cart_db_entry { rom_id: c"NB5".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Biohazard 2".as_ptr() },
    cart_db_entry { rom_id: c"NB6".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Super B-Daman: Battle Phoenix 64".as_ptr() },
    cart_db_entry { rom_id: c"NB7".as_ptr(), regions: c"EJPU".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Banjo-Tooie".as_ptr() },
    cart_db_entry { rom_id: c"NBC".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Blast Corps".as_ptr() },
    cart_db_entry { rom_id: c"NBD".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Bomberman Hero".as_ptr() },
    cart_db_entry { rom_id: c"NBH".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Body Harvest".as_ptr() },
    cart_db_entry { rom_id: c"NBK".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Banjo-Kazooie".as_ptr() },
    cart_db_entry { rom_id: c"NBM".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Bomberman 64".as_ptr() },
    cart_db_entry { rom_id: c"NBN".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Bakuretsu Muteki Bangaioh".as_ptr() },
    cart_db_entry { rom_id: c"NBV".as_ptr(), regions: c"EJ".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Bomberman 64: The Second Attack!".as_ptr() },
    cart_db_entry { rom_id: c"NCC".as_ptr(), regions: c"DEP".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Command & Conquer".as_ptr() },
    cart_db_entry { rom_id: c"NCG".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Choro Q 64 2: Hacha-Mecha Grand Prix Race".as_ptr() },
    cart_db_entry { rom_id: c"NCH".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Chopper Attack".as_ptr() },
    cart_db_entry { rom_id: c"NCK".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"NBA Courtside 2".as_ptr() },
    cart_db_entry { rom_id: c"NCR".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Penny Racers".as_ptr() },
    cart_db_entry { rom_id: c"NCT".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Chameleon Twist".as_ptr() },
    cart_db_entry { rom_id: c"NCU".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Cruis'n USA".as_ptr() },
    cart_db_entry { rom_id: c"NCW".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Cruis'n World".as_ptr() },
    cart_db_entry { rom_id: c"NCX".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Custom Robo".as_ptr() },
    cart_db_entry { rom_id: c"NCZ".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Custom Robo V2".as_ptr() },
    cart_db_entry { rom_id: c"ND2".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Doraemon 2: Nobita to Hikari no Shinden".as_ptr() },
    cart_db_entry { rom_id: c"ND3".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Akumajou Dracula Mokushiroku".as_ptr() },
    cart_db_entry { rom_id: c"ND4".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Akumajou Dracula Mokushiroku Gaiden: Legend of Cornell".as_ptr() },
    cart_db_entry { rom_id: c"ND6".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Densha de Go! 64".as_ptr() },
    cart_db_entry { rom_id: c"NDA".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Derby Stallion 64".as_ptr() },
    cart_db_entry { rom_id: c"NDK".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Space Dynamites".as_ptr() },
    cart_db_entry { rom_id: c"NDO".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Donkey Kong 64".as_ptr() },
    cart_db_entry { rom_id: c"NDP".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Dinosaur Planet".as_ptr() },
    cart_db_entry { rom_id: c"NDR".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Doraemon: Nobita to 3tsu no Seireiseki".as_ptr() },
    cart_db_entry { rom_id: c"NDU".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Duck Dodgers".as_ptr() },
    cart_db_entry { rom_id: c"NDY".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Diddy Kong Racing".as_ptr() },
    
    cart_db_entry { rom_id: c"NEA".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"PGA European Tour".as_ptr() },
    cart_db_entry { rom_id: c"NEP".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Star Wars Episode I: Racer".as_ptr() },
    cart_db_entry { rom_id: c"NER".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"AeroFighters Assault (USA)".as_ptr() },
    cart_db_entry { rom_id: c"NEV".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Neon Genesis Evangelion".as_ptr() },
    cart_db_entry { rom_id: c"NF2".as_ptr(), regions: c"P".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"F-1 World Grand Prix II".as_ptr() },
    cart_db_entry { rom_id: c"NFG".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Fighter Destiny 2".as_ptr() },
    cart_db_entry { rom_id: c"NFH".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Bass Hunter 64".as_ptr() },
    cart_db_entry { rom_id: c"NFU".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Conker's Bad Fur Day".as_ptr() },
    cart_db_entry { rom_id: c"NFW".as_ptr(), regions: c"DEFJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"F-1 World Grand Prix".as_ptr() },
    cart_db_entry { rom_id: c"NFX".as_ptr(), regions: c"EJPU".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Star Fox 64".as_ptr() },
    cart_db_entry { rom_id: c"NFY".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Kakutou Denshou: F-Cup Maniax".as_ptr() },
    cart_db_entry { rom_id: c"NFZ".as_ptr(), regions: c"P".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"F-Zero X (PAL)".as_ptr() },
    cart_db_entry { rom_id: c"NG6".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Ganbare Goemon: Dero Dero Douchuu Obake Tenkomori".as_ptr() },
    cart_db_entry { rom_id: c"NGC".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"GT 64: Championship Edition".as_ptr() },
    cart_db_entry { rom_id: c"NGE".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"GoldenEye 007".as_ptr() },
    cart_db_entry { rom_id: c"NGL".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Getter Love!!".as_ptr() },
    cart_db_entry { rom_id: c"NGP".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Goemon: Mononoke Sugoroku".as_ptr() },
    cart_db_entry { rom_id: c"NGT".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"City-Tour GP: Zen-Nihon GT Senshuken".as_ptr() },
    cart_db_entry { rom_id: c"NGU".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Tsumi to Batsu: Hoshi no Keishousha".as_ptr() },
    cart_db_entry { rom_id: c"NGV".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Glover".as_ptr() },
    cart_db_entry { rom_id: c"NHA".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Bomber Man 64 (Japan)".as_ptr() },
    cart_db_entry { rom_id: c"NHF".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"64 Hanafuda: Tenshi no Yakusoku".as_ptr() },
    cart_db_entry { rom_id: c"NHP".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Heiwa Pachinko World 64".as_ptr() },
    cart_db_entry { rom_id: c"NHY".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Hybrid Heaven (Japan)".as_ptr() },
    cart_db_entry { rom_id: c"NIB".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Itoi Shigesato no Bass Tsuri No. 1 Kettei Ban!".as_ptr() },
    cart_db_entry { rom_id: c"NIC".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Indy Racing 2000".as_ptr() },
    cart_db_entry { rom_id: c"NIJ".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Indiana Jones and the Infernal Machine".as_ptr() },
    cart_db_entry { rom_id: c"NIM".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Ide Yosuke no Mahjong Juku".as_ptr() },
    cart_db_entry { rom_id: c"NIR".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Utchan Nanchan no Hono no Challenger: Denryuu Ira Ira Bou".as_ptr() },
    cart_db_entry { rom_id: c"NJ5".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Jikkyou Powerful Pro Yakyuu 5".as_ptr() },
    cart_db_entry { rom_id: c"NJD".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Jet Force Gemini (Kiosk Demo)".as_ptr() },
    cart_db_entry { rom_id: c"NJF".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Jet Force Gemini".as_ptr() },
    cart_db_entry { rom_id: c"NJG".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Jinsei Game 64".as_ptr() },
    cart_db_entry { rom_id: c"NJM".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Earthworm Jim 3D".as_ptr() },
    cart_db_entry { rom_id: c"NK2".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Snowboard Kids 2".as_ptr() },
    cart_db_entry { rom_id: c"NK4".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Kirby 64: The Crystal Shards".as_ptr() },
    cart_db_entry { rom_id: c"NKA".as_ptr(), regions: c"DEFJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Fighters Destiny".as_ptr() },
    cart_db_entry { rom_id: c"NKG".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"MLB featuring Ken Griffey Jr.".as_ptr() },
    cart_db_entry { rom_id: c"NKI".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Killer Instinct Gold".as_ptr() },
    cart_db_entry { rom_id: c"NKJ".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Ken Griffey Jr.'s Slugfest".as_ptr() },
    cart_db_entry { rom_id: c"NKT".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Mario Kart 64".as_ptr() },
    cart_db_entry { rom_id: c"NLB".as_ptr(), regions: c"P".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Mario Party (PAL)".as_ptr() },
    cart_db_entry { rom_id: c"NLL".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Last Legion UX".as_ptr() },
    cart_db_entry { rom_id: c"NLR".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Lode Runner 3D".as_ptr() },
    cart_db_entry { rom_id: c"NM6".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Mega Man 64".as_ptr() },
    cart_db_entry { rom_id: c"NM8".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Mario Tennis".as_ptr() },
    cart_db_entry { rom_id: c"NMF".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Mario Golf".as_ptr() },
    cart_db_entry { rom_id: c"NMG".as_ptr(), regions: c"DEP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Monaco Grand Prix".as_ptr() },
    cart_db_entry { rom_id: c"NMI".as_ptr(), regions: c"DEFIPS".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Mission: Impossible".as_ptr() },
    cart_db_entry { rom_id: c"NML".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Mickey's Speedway USA".as_ptr() },
    cart_db_entry { rom_id: c"NMO".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Monopoly".as_ptr() },
    cart_db_entry { rom_id: c"NMQ".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Paper Mario".as_ptr() },
    cart_db_entry { rom_id: c"NMR".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Multi Racing Championship".as_ptr() },
    cart_db_entry { rom_id: c"NMS".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Morita Shougi 64".as_ptr() },
    cart_db_entry { rom_id: c"NMU".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Big Mountain 2000".as_ptr() },
    cart_db_entry { rom_id: c"NMV".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Mario Party 3".as_ptr() },
    cart_db_entry { rom_id: c"NMW".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Mario Party 2".as_ptr() },
    cart_db_entry { rom_id: c"NMX".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Excitebike 64".as_ptr() },
    cart_db_entry { rom_id: c"NN6".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Dr. Mario 64".as_ptr() },
    cart_db_entry { rom_id: c"NNA".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Star Wars Episode I: Battle for Naboo".as_ptr() },
    cart_db_entry { rom_id: c"NNB".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Kobe Bryant in NBA Courtside".as_ptr() },
    cart_db_entry { rom_id: c"NOB".as_ptr(), regions: c"EJ".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Ogre Battle 64: Person of Lordly Caliber".as_ptr() },
    cart_db_entry { rom_id: c"NOS".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"64 Oozumou".as_ptr() },
    cart_db_entry { rom_id: c"NP2".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Chou Kuukan Nighter Pro Yakyuu King 2".as_ptr() },
    cart_db_entry { rom_id: c"NP3".as_ptr(), regions: c"DEFIJPS".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Pokemon Stadium 2".as_ptr() },
    cart_db_entry { rom_id: c"NP6".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Jikkyou Powerful Pro Yakyuu 6".as_ptr() },
    cart_db_entry { rom_id: c"NPA".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Jikkyou Powerful Pro Yakyuu 2000".as_ptr() },
    cart_db_entry { rom_id: c"NPD".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Perfect Dark".as_ptr() },
    cart_db_entry { rom_id: c"NPE".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Jikkyou Powerful Pro Yakyuu Basic Ban 2001".as_ptr() },
    cart_db_entry { rom_id: c"NPF".as_ptr(), regions: c"DEFIJPSU".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Pokemon Snap".as_ptr() },
    cart_db_entry { rom_id: c"NPG".as_ptr(), regions: c"EJ".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Hey You, Pikachu!".as_ptr() },
    cart_db_entry { rom_id: c"NPH".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Pokemon Snap Station (Kiosk Demo)".as_ptr() },
    cart_db_entry { rom_id: c"NPM".as_ptr(), regions: c"P".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Premier Manager 64".as_ptr() },
    cart_db_entry { rom_id: c"NPN".as_ptr(), regions: c"DEFP".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Pokemon Puzzle League".as_ptr() },
    cart_db_entry { rom_id: c"NPO".as_ptr(), regions: c"DEFIPS".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Pokemon Stadium (USA, PAL)".as_ptr() },
    cart_db_entry { rom_id: c"NPP".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Parlor! Pro 64: Pachinko Jikki Simulation Game".as_ptr() },
    cart_db_entry { rom_id: c"NPS".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Jikkyou J.League 1999: Perfect Striker 2".as_ptr() },
    cart_db_entry { rom_id: c"NPT".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Puyo Puyon Party".as_ptr() },
    cart_db_entry { rom_id: c"NPW".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Pilotwings 64".as_ptr() },
    cart_db_entry { rom_id: c"NPY".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Puyo Puyo Sun 64".as_ptr() },
    cart_db_entry { rom_id: c"NR7".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Robot Poncots 64: 7tsu no Umi no Caramel".as_ptr() },
    cart_db_entry { rom_id: c"NRA".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Rally '99".as_ptr() },
    cart_db_entry { rom_id: c"NRC".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Top Gear Overdrive".as_ptr() },
    cart_db_entry { rom_id: c"NRE".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Resident Evil 2".as_ptr() },
    cart_db_entry { rom_id: c"NRH".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Rockman Dash".as_ptr() },
    cart_db_entry { rom_id: c"NRI".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"The New Tetris".as_ptr() },
    cart_db_entry { rom_id: c"NRS".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Star Wars: Rogue Squadron".as_ptr() },
    cart_db_entry { rom_id: c"NRZ".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Ridge Racer 64".as_ptr() },
    cart_db_entry { rom_id: c"NS4".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Super Robot Taisen 64".as_ptr() },
    cart_db_entry { rom_id: c"NS6".as_ptr(), regions: c"EJ".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Star Soldier: Vanishing Earth".as_ptr() },
    cart_db_entry { rom_id: c"NSA".as_ptr(), regions: c"JP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"AeroFighters Assault (PAL, Japan)".as_ptr() },
    cart_db_entry { rom_id: c"NSC".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Starshot: Space Circus Fever".as_ptr() },
    cart_db_entry { rom_id: c"NSI".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Fushigi no Dungeon: Fuurai no Shiren 2".as_ptr() },
    cart_db_entry { rom_id: c"NSM".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Super Mario 64".as_ptr() },
    cart_db_entry { rom_id: c"NSN".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Snow Speeder".as_ptr() },
    cart_db_entry { rom_id: c"NSQ".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"StarCraft 64".as_ptr() },
    cart_db_entry { rom_id: c"NSS".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Super Robot Spirits".as_ptr() },
    cart_db_entry { rom_id: c"NSU".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Rocket: Robot on Wheels".as_ptr() },
    cart_db_entry { rom_id: c"NSV".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"SpaceStation Silicon Valley".as_ptr() },
    cart_db_entry { rom_id: c"NSW".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Star Wars: Shadows of the Empire".as_ptr() },
    cart_db_entry { rom_id: c"NT3".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Toukon Road 2".as_ptr() },
    cart_db_entry { rom_id: c"NT6".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Tetris 64".as_ptr() },
    cart_db_entry { rom_id: c"NT9".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Tigger's Honey Hunt".as_ptr() },
    cart_db_entry { rom_id: c"NTB".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Transformers: Beast Wars Metals 64".as_ptr() },
    cart_db_entry { rom_id: c"NTC".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"64 Trump Collection".as_ptr() },
    cart_db_entry { rom_id: c"NTE".as_ptr(), regions: c"AP".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"1080 Snowboarding".as_ptr() },
    cart_db_entry { rom_id: c"NTJ".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Tom and Jerry in Fists of Furry".as_ptr() },
    cart_db_entry { rom_id: c"NTM".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Mischief Makers".as_ptr() },
    cart_db_entry { rom_id: c"NTN".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"All-Star Tennis 99".as_ptr() },
    cart_db_entry { rom_id: c"NTP".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Tetrisphere".as_ptr() },
    cart_db_entry { rom_id: c"NTR".as_ptr(), regions: c"JP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Top Gear Rally (PAL, Japan)".as_ptr() },
    cart_db_entry { rom_id: c"NTW".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"64 de Hakken!! Tamagotchi".as_ptr() },
    cart_db_entry { rom_id: c"NTX".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Taz Express".as_ptr() },
    cart_db_entry { rom_id: c"NUB".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"PD Ultraman Battle Collection 64".as_ptr() },
    cart_db_entry { rom_id: c"NUM".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Nushi Zuri 64: Shiokaze ni Notte".as_ptr() },
    cart_db_entry { rom_id: c"NUT".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Nushi Zuri 64".as_ptr() },
    cart_db_entry { rom_id: c"NVB".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Bass Rush: ECOGEAR PowerWorm Championship".as_ptr() },
    cart_db_entry { rom_id: c"NVL".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"V-Rally 99 (USA, PAL)".as_ptr() },
    cart_db_entry { rom_id: c"NVP".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Virtual Pro Wrestling 64".as_ptr() },
    cart_db_entry { rom_id: c"NVY".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"V-Rally 99 (Japan)".as_ptr() },
    cart_db_entry { rom_id: c"NW2".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"WCW/nWo Revenge".as_ptr() },
    cart_db_entry { rom_id: c"NW4".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"WWF No Mercy".as_ptr() },
    cart_db_entry { rom_id: c"NWC".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Wild Choppers".as_ptr() },
    cart_db_entry { rom_id: c"NWL".as_ptr(), regions: c"EP".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Waialae Country Club: True Golf Classics".as_ptr() },
    cart_db_entry { rom_id: c"NWQ".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Rally Challenge 2000".as_ptr() },
    cart_db_entry { rom_id: c"NWR".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Wave Race 64".as_ptr() },
    cart_db_entry { rom_id: c"NWT".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Wetrix (Japan)".as_ptr() },
    cart_db_entry { rom_id: c"NWU".as_ptr(), regions: c"P".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Worms Armageddon (PAL)".as_ptr() },
    cart_db_entry { rom_id: c"NWX".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"WWF WrestleMania 2000".as_ptr() },
    cart_db_entry { rom_id: c"NXO".as_ptr(), regions: c"E".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Cruis'n Exotica".as_ptr() },
    cart_db_entry { rom_id: c"NYK".as_ptr(), regions: c"J".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_4KBIT, description: c"Yakouchuu II: Satsujin Kouro".as_ptr() },
    cart_db_entry { rom_id: c"NYS".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_EEPROM_16KBIT, description: c"Yoshi's Story".as_ptr() },
    cart_db_entry { rom_id: c"NYW".as_ptr(), regions: c"EJ".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Harvest Moon 64".as_ptr() },
    cart_db_entry { rom_id: c"NZL".as_ptr(), regions: c"P".as_ptr(), save_type: CART_DB_SAVE_TYPE_SRAM_256KBIT, description: c"Legend of Zelda: Ocarina of Time (PAL)".as_ptr() },
    cart_db_entry { rom_id: c"NZS".as_ptr(), regions: c"EJP".as_ptr(), save_type: CART_DB_SAVE_TYPE_FLASH_1MBIT, description: c"Legend of Zelda: Majora's Mask".as_ptr() },
];

